### ISSUE TITLE
Very nice - first try with sample action fails

### ISSUE THREAD

**Issue by luebbe** [frenck/action-home-assistant#1]
Very nice, thanks a lot!

However my first try fails with:

Failed to resolve action download info. Error: Unable to resolve action `frenck/action-home-assistant@v1`, unable to find version `v1`

See: https://github.com/luebbe/HomeAssistantConfig/runs/1693521073?check_suite_focus=true

**Comment by frenck** [comment]
Yeah I was not actually ready yet 👍 

Sorry about that, will finish up my work here 😬

**Comment by luebbe** [comment]
No problem :D 
Thanks for all your great work!

**Comment by frenck** [comment]
Your welcome sir!

If you re-run your workflow, it should work now.

**Comment by luebbe** [comment]
Yes it does, thank you. So you got quick user feedback from me today ;)

**Comment by frenck** [comment]
Well, thank you for jumping in and providing that feedback!

I've seen your latest run showed some interesting stuff I can use to improve this action even more.

<https://github.com/frenck/action-home-assistant/discussions/9>

Thanks! 👍

**Comment by luebbe** [comment]
Go ahead, it's an old config, which throws quite a few warnings. If you want to use it as a playground, I won't push my latest version yet.
