### ISSUE TITLE
Mock ssl certificates

### ISSUE THREAD

**Issue by dylandoamaral** [frenck/action-home-assistant#22]
Hey, first of all, what a beautifull ecoystem !

I am currently using ssl certificates inside my configurations (`'/ssl/fullchain.pem` and `/ssl/privkey.pem` in http yaml section) and I don't want to push theses files in github. Such as secrets, I would like to mock theses files or I need to ignore somehow that they should exist. Do you have a way to that ?

**Comment by dylandoamaral** [comment]
Never mind, I am such an idiot. Just find the solution, one minute after writing this issue... For people in the same situation, you could just use the ssl path as a secret and change the path to dummy files using the fake secrets.yaml!

**Comment by frenck** [comment]
Took you just 4 minutes to figure out after creating the issue 😄 

Glad you got it figured out m8!

**Comment by dylandoamaral** [comment]
Yes I was looking for a solution during more than a hour and then immediately after the issue, the idea came into my head.

Sorry for that, at least it may help some people in the future !
