### ISSUE TITLE
Support for environment variables

### ISSUE THREAD

**Issue by Whazor** [frenck/action-home-assistant#43]
Currently I provide secrets via `!env_var` and have an env stub file that I would like to use for testing my home assistant configuration.

**Comment by frenck** [comment]
Interesting case, that would indeed be a nice addition.

**Comment by Whazor** [comment]
Via a file env_file as optional input of the action where you can give up an .env file, then it will add --env-file to the docker check command. This will allow you to use !env_var inside of your home assistant config and have an env stub where you store secrets/variables.

This is a common pattern for people running Home Assistant in Kubernetes via [k8s at home](https://k8s-at-home.com/) and where people mount secrets via environment variables, such that you can use encrypted secrets via [SOPS](https://github.com/mozilla/sops).
